# -*- coding: utf-8 -*-
"""regressao_knn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RcV8SEUF6792yEug3b7OYpwa5AYnGw10
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/ConsumoCo2.csv")
df

motores = df[["ENGINESIZE"]]
co2 = df[["CO2EMISSIONS"]]

motores

"""#Regressão Linear"""

x_train, x_test, y_train, y_test = train_test_split(motores,co2, test_size=0.3, random_state=42)

print(motores.iloc[0], co2.iloc[0])

plt.scatter(x_train, y_train, color = "red")
plt.xlabel("Motores")
plt.ylabel("Emissão de CO2")
plt.show()

model = linear_model.LinearRegression()
model.fit(x_train, y_train)
model.intercept_, model.coef_

plt.scatter(x_train, y_train, color = "blue")
plt.plot(x_train, model.coef_[0][0]*x_train + model.intercept_[0], "-r")
plt.xlabel("Motores")
plt.ylabel("CO2")
plt.show()

"""#Agora utilizando o KNN"""

knn_model = KNeighborsRegressor()
knn_model.fit(x_train, y_train)

"""#Agora realizando testes"""

y_pred_knn = knn_model.predict(x_test)

r2_knn = r2_score(y_test, y_pred_knn)
mse_knn = mean_squared_error(y_test, y_pred_knn)
mae_knn = mean_absolute_error(y_test, y_pred_knn)

y_pred_lr = lr_model.predict(x_test)

r2_lr = r2_score(y_test, y_pred_lr)
mse_lr = mean_squared_error(y_test, y_pred_lr)
mae_lr = mean_absolute_error(y_test, y_pred_lr)

print("KNN:")
print("R²:", r2_knn)
print("MSE:", mse_knn)
print("MAE:", mae_knn)

print("\nRegressão Linear:")
print("R²:", r2_lr)
print("MSE:", mse_lr)
print("MAE:", mae_lr)